#!/bin/bash
clear
echo -e "       =============================
       [ \033[1;31mG\033[37m-\033[1;32mO\033[37m-\033[1;33mB\033[37m-\033[1;34mL\033[37m-\033[1;35mO\033[37m-\033[1;36mK\033[0m \033[1;31mT\033[37m-\033[1;32mO\033[37m-\033[1;33mO\033[37m-\033[1;34mL\033[37m-\033[1;35mK\033[37m-\033[1;36mI\033[37m-\033[1;31mT\033[0m ]
       ============================="
echo -e "\n\033[1;31m  [!] Created By [!]\033[32m"
echo -e "  \033[0m>>>\033[32;1m Syifani Abdullah"
echo -e "  \033[0m |_ Click Langsung => \033[32;1mhttps://fb.com/GantengMaks"
echo -e "  \033[0m>>>\033[32;1m Nunul Azmi"
echo -e "  \033[0m>>>\033[32;1m ~Gans"
echo -e "  \033[0m |_ Click Langsung => \033[32;1mhttps://fb.com/GantengMaks"
echo -e "  \033[0m>>>\033[32;1m ./Xi4u7"
echo -e "  \033[0m |_ Click Langsung => \033[32;1mhttps://fb.com/GantengMaks"
echo -e "\n  \033[1;31m[!] Import To Termux By [!]\033[1;32m"
echo -e "  \033[0m>>>\033[1;32mbon'007"
echo -e "  \033[0m |_ Click Langsung => \033[32;1mhttps://fb.com/GantengMaks"
echo -e "  \033[0m>>>\033[1;32mJack O'neil"
echo -e "  \033[0m |_ Click Langsung => \033[32;1mhttps://fb.com/GantengMaks\n"

echo -e "  \033[0m>>>\033[32;1mSorry Setelah Update Review Ulang Creator Pertama + Kedua Udah ga pernah Keliatan lagi maaf codenamenya ga disebutin"

echo -e "  \033[0m>>>\033[32;1m Tools Kemudian Dikembangkan Oleh J_Lnyx69 & Mr_/bon'007"
echo -e "  \033[0m>>>\033[32;1m Player Old Pasti Tau Ama Tools Legend Ini"
echo -e "  >>> Mungkin ada sebagian Tool yg membutuhkan akses root !"
echo -e "\033[0m\n\n"
echo ""
echo -e "\033[1;32m\nKetik ./start untuk memulai GBLK\033[0m"
echo -e "Tekan ENTER untuk lanjut"
read about
