#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from urllib2 import Request, urlopen, URLError, HTTPError

def Space(j):
	i = 0
	while i<=j:
		print " ",
		i+=1

import os
os.system('clear')

def findAdmin():
	f = open("path.txt","r");
	link = raw_input("Masukan Site Target \n(Contoh : bokepdo.com or www.bokepdo.com ): ")
	print "\n\nPath Login Ditemukan : \n"
	while True:
		sub_link = f.readline()
		if not sub_link:
			break
		req_link = "http://"+link+"/"+sub_link
		req = Request(req_link)
		try:
			response = urlopen(req)
		except HTTPError as e:
			continue
		except URLError as e:
			continue
		else:
			print " => ",req_link

def Credit():
	Space(7); print "\n        ..::|[ Admin Finder ]|::..\n"

Credit()
findAdmin()

import subprocess
subprocess.call("sh adf", shell=True)