#!/bin/bash
clear
clear

echo "
            \033[32;1m..::|[ Facebook auto like and coment ]|::.. \033[0m "
echo "






"
cd ../xx/bot
python2 bot.py

echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
clear
sh start
fi

if [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi


