#!/bin/bash
clear
echo "

"

echo "         \033[32;1m..::|[ MD5 hash ]|::.. \033[0m  "
echo "





"

echo -n "\n\033[33;1mMasukan password yg mau di hash: \033[0m "
read md5

echo "




"
cd ../xx
python2 hash $md5


echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
sh start

elif [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi


