#!/system/xbin/bash


clear
clear
clear

echo "\n


"
echo "       \033[32;1m..::|[ CMSmap ]|::.. \033[0m        "
echo "\n"

echo -n "\033[33;1mMasukan Target : \033[0m "
read trgt
echo -n "\033[33;1mWordpress(W)/Joomla(J)/Drupal(D) ???\033[0m "
read file

cd ../xxx
python2 cms -t $trgt -f $file --noedb



echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
sh start

elif [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi


