#!/bin/bash
clear

echo "

"
echo "         \033[32;1m..::|[ MD5 Cracker ]|::.. \033[0m        "

echo "\n




"
echo -n "\n\033[33;1mMasukan hash yg mau di Crack: \033[0m"
read trgt
echo "







"
cd ../xx/


python2 md5 $trgt ../wodlis/passwords.lst



echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
clear
sh start


elif [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi


