#!/bin/bash
clear
echo "
            \033[32;1m..::|[ DNS BruteForce ]|::..\033[0m"
echo "













"
echo -n "\n\033[31;1mMasukan Server : \033[0m"
read user
echo "

"
echo " \033[32;1m"
cd ../xx/
python2 dnsbrute $user ../wodlis/passwords.lst
echo " \033[0m"


echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
clear
sh start
fi

if [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi
