#!/bin/bash
clear


echo "           \033[32;1m..::|[ Hash Generator ]|::..\033[0m"

echo "












"
echo -n "\033[31;1mMasukan Password : \033[0m"
read cuk
clear
echo "\033[31;1mPassword :\033[0m \033[35;1m$cuk\033[0m"

cd ../xx/

python2 hashgenerator $cuk



echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
clear
sh start
fi

if [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi

