#!/bin/bash

clear
echo "             \033[32;1m..::|[ Nmap Http BruteForce ]|::..\033[0m"
echo "






"

echo -n "Masukan Target: "
read ff
echo "\nTarget: $ff"

echo -n "Masukan Path: "
read pat
echo "\nPath: $pat"

nmap -p 80 --script http-brute -script-args http-brute.path=$pat $ff
echo "


"


echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
clear
sh start
fi

if [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi
