#!/bin/bash

clear
echo "             \033[32;1m..::|[ Nmap MySQL BruteForce ]|::..\033[0m"
echo "






"

echo -n "\033[32;1mMasukan target: "
read ayam
echo "\nTarget: $ayam"
echo " "
echo "[#]Memulai!![#]\033[0m"

nmap -p 3306 --script mysql-brute.nse $ayam -d

echo "


"

echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
clear
sh start
fi

if [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi

