#!/system/xbin/bash

clear
echo "             \033[32;1m..::|[ Nmap Http BruteForce ]|::..\033[0m"
echo "






"

echo -n "Target Kamu: "
read sss
echo "\nTarget: $sss"
nmap -sV --script=http-sql-injection $sss -Pn -p 80 -d
echo "


"

echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
clear
sh start
fi

if [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi
