#!/bin/bash

clear
echo "   
        \033[32;1m..::|[ Port Service Scanner ]|::.. \033[0m
"
echo "[?] Apakah \033[4;32mArfian Dicky Firmansyah\033[0m Itu \033[32mTAMVAN\033[0m?\n==> Ya (y/Y) \n==> Ga (g/G)"
echo -n "==> Pilihan: "
read peler
echo -n "\n==> Dipilih: $peler"
if [ $peler = y ] || [ $peler = Y ]
then
  echo -n "\n[~] Masukan Target: "
  read prt
  echo "\n[~] Target: \033[32m$prt\033[0m"
  echo "[?] Tekan \033[32mL \033[0mUntuk Lanjut"
  echo "[?] Tekan \033[33mM \033[0mUntuk Masukan Ulang"
  echo -n "==> Pilihan: "
  read pili
    if [ $pili = L ] || [ $pili = l ]
    then
    echo "\n[~] Proses Scanning Pada: \033[32m$prt\033[0m"
    nmap $prt | awk '/tcp/{print "\n\033[32m [+]\033[0m Port: " $1 "\n\033[33m    [-]\033[0m Status: " $2 "\n\033[33m    [-]\033[0m Service: " $3 "\n\033[33m    [-]\033[0m Running: " $4 " " $5 " " $6 " " $7 " " $8 " " $9 " " $10 " " $11 " " $12 " " $13 " " $14 " " $15 " " $16 " " $17 " " $18 " " ;}'
    echo "\n[~] Scan Selesai"
    fi
    
    if  [ $pili = M ] || [ $pili = m ]
    then
    sh prot
    fi
fi

if [ $peler = g ] || [ $peler = G ]
then
clear
echo "\n\n      \033[1;31mKONTOLMU KECIL CUK!\033[0m"
fi


echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
clear
sh start
fi

if [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi
