#!/bin/bash

clear
echo "   
        \033[32;1m..::|[ Host Scanner ]|::.. \033[0m
"
ipgtw=$(ip route | awk '/default/ { print $3 }')
echo "
[~] IP range local : \033[32m$ipgtw/24\033[0m"
echo -n "[~] Masukan ip range: "
read gem
echo "\n[~] Target range = \033[4;33m$gem\033[0m"
echo "
\033[1;31m[#]\033[0m Proses Scanning..."
nmap -O -F -T5 $gem | awk '/MAC Address:/{print "\033[0m  [-] Nama Device : "$4 " " $5 " " $6 " " $7;}/Nmap scan report for/{print "\n\033[1;32m[+] Ip : " $5;}/MAC Address:/{print "  [-] Mac : "$3;}/Running: /{print "  [-]" " OS : " $2 " | Tipe : " $3 $4;} /Failed to resolve/{print "\033[1;31m[!] Masukan Target Yang Bener Coeg! \033[0m" ;}'
echo "\033[0m
[#] Scan Selesai
"
echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
clear
sh start
fi

if [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi
