#!/bin/bash
echo "\n



"
echo "                 \033[32;1m..::|[ JOOMLA SQL vuln scanner ]|::.. \033[0m                  "


echo -n "\n menurutmu Arfian Dicky F ganteng gak \033[32;1m(Y) \033[0m ya \033[32;1m(G) \033[0m gak : "
read ok
echo -n "\n[+]==>> Dipilih : $ok "
[ $ok = y ] || [ $ok = Y ]
echo "\n


"
echo -n "\n masukan target disini : "
read trgt
echo "\n

"
cd ../xx/

py jomsq $trgt 




if [ $ok = g ] || [ $ok = G ]
then
clear
echo "\n\n      \033[1;31mANJIRR MATA LU SUWEK LU DI KICK CUK\033[0m"
fi


echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
clear
sh start
fi

if [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi


