#!/bin/bash

clear
echo "1" > /proc/sys/net/ipv4/ip_forward
echo "   
           \033[32;1m..::|[ WordPress BruteForce ]|::.. \033[0m
"
echo "\033[1;33m[!] \033[0mTools Ini Hanya Dapat Digunakan Jika Halaman Login Berada di
==> \033[1;32mSite.com/wp-login.php\033[30m
\033[1;33m[!] \033[0mTidak Dapat Digunakan Jika Halaman Login Berada Pada Sub Path
==> \033[1;31mSite.com/taik/gblk/wp-login.php\033[0m

\033[1;33m[!] \033[0mPada Bagian Target Tuliskan Sitenya Saja
==> \033[1;32mSite.com\033[30m
\033[1;33m[!] \033[0mBukan
==> \033[1;31mHttps://www.Site.com

\033[1;33m[!] \033[0mTools Ini Sangat Membutuhkan Wordlist Akurat
\033[1;33m[!] \033[0mAnda Dapat Menambah Atau Mengganti Wordlistnya
\033[0m==> \033[1;33m/Sdcard/wodlis/passwords.lst
\033[0m==> \033[1;33m/Sdcard/wodlis/usernames.lst

\033[0m"
echo -n "[?] Lanjut (y)ya / (g)moh : "
read kentot
echo "\n"
echo "==> Pilihan $kentot"
if [ $kentot = y ] || [ $kentot = Y ]
then
   echo "[?] Apakah Anda HVMV?"
   echo "==> Ya, Saya HVMV  (y/Y)"
   echo "==> Bukan, Saya GAY :v (g/G)"
   echo -n "==> Pilihan: "
   read gay
   echo "\n==> Pilihan: $gay"
   if [ $gay = g ] || [ $gay = G ] || [ $gay = y ] || [ $gay = Y ]
   then
   clear
   sh wp-brute
   fi
fi

if [ $kentot = g ] || [ $kentot = G ]
then
clear
sh start
fi