#!/bin/bash


clear
clear
clear

echo "\n


"
echo "    \033[32;1m..::|[ wordpres scan vulnebirity ]|::..\033[0m"
echo "





"
echo -n "\033[37;1mMasukan Target: \033[0m"
read trgt
echo "\n     






"

cd ../xx

python2 wpscan $trgt


echo "
=> Tekan \033[33mB\033[0m untuk kembali
=> Tekan \033[31mK\033[0m untuk keluar"
echo -n "=> Pilihan: "
read upil
if [ $upil = b ] || [ $upil = B ]
then
clear
sh start
fi

if [ $upil = k ] || [ $upil = K ]
then
clear
sh exit
fi

