#!/usr/bin/python

import md5, sys

if len(sys.argv) != 2:
	print "\033[31;1mMamsukan password yg mau lu jadiin md5 coeg.!! \033[0m"
	sys.exit(1)
	
pw = sys.argv[1]
hash = md5.new()
hash.update(pw)
print "\n\033[32;1mHasil Password \033[0m:"
print hash.hexdigest()
